// LVGL 8.4.0 configuration for SigenStorPuck.
//
// This is deliberately a *partial* config, not a copy of lv_conf_template.h.
// LVGL's lv_conf_internal.h guards every option with #ifndef and supplies a
// default, so only the settings this project actually changes appear here —
// which keeps the diff meaningful when LVGL is upgraded.
//
// Found via -D LV_CONF_INCLUDE_SIMPLE (see platformio.ini); PlatformIO puts
// include/ on the global include path, so the sim environment picks up the same
// file with no extra plumbing.

#ifndef LV_CONF_H
#define LV_CONF_H

#include <stdint.h>

// ---------------------------------------------------------------- colour ----

// RGB565. The CO5300 is fed by draw16bitRGBBitmap(), which wants native byte
// order, so no byte swap.
#define LV_COLOR_DEPTH 16
#define LV_COLOR_16_SWAP 0

// ---------------------------------------------------------------- memory ----

// LVGL's own object/style pool. Large bitmaps are allocated separately in PSRAM
// rather than being sized into this (docs/PLAN.md §B1).
#define LV_MEM_CUSTOM 0
#define LV_MEM_SIZE (64U * 1024U)

// ------------------------------------------------------------------ time ----

// Drive LVGL's clock from the host's own millisecond counter instead of calling
// lv_tick_inc() from a timer interrupt — one less thing to get wrong, and the
// network task in §B3 cannot starve it.
#define LV_TICK_CUSTOM 1
#if defined(ARDUINO)
#define LV_TICK_CUSTOM_INCLUDE "Arduino.h"
#define LV_TICK_CUSTOM_SYS_TIME_EXPR (millis())
#else
// sim environment: same LVGL, same config, SDL's clock. Unqualified "SDL.h"
// because sdl2-config --cflags puts the SDL2 directory itself on the path.
#define LV_TICK_CUSTOM_INCLUDE "SDL.h"
#define LV_TICK_CUSTOM_SYS_TIME_EXPR (SDL_GetTicks())
#endif

// ~60 Hz. The panel and QSPI bus can sustain it.
#define LV_DISP_DEF_REFR_PERIOD 16
#define LV_INDEV_DEF_READ_PERIOD 16

// --------------------------------------------------------------- geometry ----

// 466 px across roughly 1.75", so default padding and widget sizes scale about
// right for a display held at arm's length.
#define LV_DPI_DEF 130

// ----------------------------------------------------------------- fonts ----

// Our own Montserrat subsets from src/ui/fonts/, generated by
// tools/generate_fonts.sh. Same typeface and weight as LVGL's built-ins, but
// they also carry "£", "°" and "·" — LVGL's stock fonts are ASCII-only, and the
// Puck shows a saving in pounds and a cell temperature in degrees.
//
// The built-ins stay off: carrying two near-identical Montserrats would waste
// flash and make it easy to reach for the one that cannot render a pound sign.
#define LV_FONT_CUSTOM_DECLARE \
  LV_FONT_DECLARE(puck_font_14) \
  LV_FONT_DECLARE(puck_font_20) \
  LV_FONT_DECLARE(puck_font_28) \
  LV_FONT_DECLARE(puck_font_48)

#define LV_FONT_DEFAULT &puck_font_20

// --------------------------------------------------------------- widgets ----

// LVGL's own QR encoder, for the settings-page address on screen 5 and on the
// "Not configured" overlay. Off by default in lv_conf_internal.h. It draws into
// a 1-bit indexed canvas out of LV_MEM_SIZE, which is a couple of KB at the
// sizes used here — cheaper than carrying a second encoder, and it means the
// simulator renders exactly what the device does.
#define LV_USE_QRCODE 1

// ----------------------------------------------------------------- debug ----

// LVGL's own warnings go to the USB-CDC serial log. Raise to _INFO while
// chasing a layout problem.
#define LV_USE_LOG 1
#define LV_LOG_LEVEL LV_LOG_LEVEL_WARN
#define LV_LOG_PRINTF 1

#endif  // LV_CONF_H
