#!/usr/bin/env python3
"""Embeds test/fixtures/*.json into a header the firmware can compile in.

Temporary scaffolding for PLAN.md §C4 step 2: it lets screen work be judged on
the real panel before the network client of step 4 exists. Generated from the
same fixtures the simulator uses, so the device and the sim are showing exactly
the same payloads rather than two hand-copied sets that quietly drift apart.

Delete this, the generated header, and its use in src/main.cpp once /api/summary
is being fetched for real.

    python3 tools/embed_fixtures.py
"""
import json
import pathlib

REPO = pathlib.Path(__file__).resolve().parent.parent
FIXTURES = REPO / "test" / "fixtures"
OUT = REPO / "src" / "dev_fixtures.h"

entries = []
for path in sorted(FIXTURES.glob("*.json")):
    # Minified: the pretty-printed form would triple the flash cost for nothing.
    payload = json.dumps(json.loads(path.read_text()), separators=(",", ":"))
    entries.append((path.stem, payload))

lines = [
    "// GENERATED by tools/embed_fixtures.py — do not edit by hand.",
    "//",
    "// Canned /api/summary payloads so screens can be checked on real hardware",
    "// before the network client exists (PLAN.md §C4 step 2). Temporary: delete",
    "// this file, its generator, and its use in src/main.cpp at step 4.",
    "",
    "#pragma once",
    "",
    "#include <stddef.h>",
    "",
    "struct DevFixture {",
    "  const char* name;",
    "  const char* json;",
    "};",
    "",
    "static const DevFixture DEV_FIXTURES[] = {",
]

for name, payload in entries:
    lines.append(f'    {{"{name}", R"JSON({payload})JSON"}},')

lines += [
    "};",
    "",
    "static const size_t DEV_FIXTURE_COUNT = sizeof(DEV_FIXTURES) / sizeof(DEV_FIXTURES[0]);",
    "",
]

OUT.write_text("\n".join(lines))
total = sum(len(payload) for _, payload in entries)
print(f"{OUT.relative_to(REPO)}: {len(entries)} fixtures, {total} bytes of JSON")
