// GENERATED by tools/embed_fixtures.py — do not edit by hand.
//
// Canned /api/summary payloads so screens can be checked on real hardware
// before the network client exists (PLAN.md §C4 step 2). Temporary: delete
// this file, its generator, and its use in src/main.cpp at step 4.

#pragma once

#include <stddef.h>

struct DevFixture {
  const char* name;
  const char* json;
};

static const DevFixture DEV_FIXTURES[] = {
    {"01_normal", R"JSON({"v":1,"ts":1784984400,"ok":true,"age":3,"power":{"pv":3.42,"grid":-1.1,"batt":1.2,"home":1.12,"ev":0.0,"plant":2.22,"off_grid":false},"battery":{"soc":78.5,"soh":99.0,"capacity_kwh":16.0,"temp_c":24.5,"eta_min":96},"today":{"solar":12.4,"import":3.1,"export":5.2,"load":9.8,"charge":6.0,"discharge":4.2},"cost":{"configured":true,"saving_gbp":1.23,"rate_p":7.5,"next":[{"from":1784986200,"p":23.1},{"from":1784988000,"p":7.5},{"from":1784989800,"p":7.5}]},"alarms":0})JSON"},
    {"02_evening_discharge", R"JSON({"v":1,"ts":1784984400,"ok":true,"age":3,"power":{"pv":0.0,"grid":0.35,"batt":-2.1,"home":2.45,"ev":0.0,"plant":2.1,"off_grid":false},"battery":{"soc":41.5,"soh":99.0,"capacity_kwh":16.0,"temp_c":22.0,"eta_min":118},"today":{"solar":12.4,"import":3.1,"export":5.2,"load":9.8,"charge":6.0,"discharge":4.2},"cost":{"configured":true,"saving_gbp":1.23,"rate_p":7.5,"next":[{"from":1784986200,"p":23.1},{"from":1784988000,"p":7.5},{"from":1784989800,"p":7.5}]},"alarms":0})JSON"},
    {"03_exporting", R"JSON({"v":1,"ts":1784984400,"ok":true,"age":3,"power":{"pv":6.8,"grid":-5.42,"batt":0.0,"home":1.38,"ev":0.0,"plant":6.8,"off_grid":false},"battery":{"soc":100.0,"soh":99.0,"capacity_kwh":16.0,"temp_c":27.5,"eta_min":null},"today":{"solar":12.4,"import":3.1,"export":5.2,"load":9.8,"charge":6.0,"discharge":4.2},"cost":{"configured":true,"saving_gbp":1.23,"rate_p":7.5,"next":[{"from":1784986200,"p":23.1},{"from":1784988000,"p":7.5},{"from":1784989800,"p":7.5}]},"alarms":0})JSON"},
    {"04_ev_charging", R"JSON({"v":1,"ts":1784984400,"ok":true,"age":3,"power":{"pv":4.1,"grid":0.6,"batt":-0.5,"home":2.0,"ev":3.2,"plant":4.6,"off_grid":false},"battery":{"soc":63.0,"soh":99.0,"capacity_kwh":16.0,"temp_c":24.5,"eta_min":74},"today":{"solar":12.4,"import":3.1,"export":5.2,"load":9.8,"charge":6.0,"discharge":4.2},"cost":{"configured":true,"saving_gbp":1.23,"rate_p":7.5,"next":[{"from":1784986200,"p":23.1},{"from":1784988000,"p":7.5},{"from":1784989800,"p":7.5}]},"alarms":0})JSON"},
    {"05_off_grid", R"JSON({"v":1,"ts":1784984400,"ok":true,"age":3,"power":{"pv":1.8,"grid":0.0,"batt":-1.1,"home":2.9,"ev":0.0,"plant":2.9,"off_grid":true},"battery":{"soc":55.0,"soh":99.0,"capacity_kwh":16.0,"temp_c":24.5,"eta_min":92},"today":{"solar":12.4,"import":3.1,"export":5.2,"load":9.8,"charge":6.0,"discharge":4.2},"cost":{"configured":true,"saving_gbp":1.23,"rate_p":7.5,"next":[{"from":1784986200,"p":23.1},{"from":1784988000,"p":7.5},{"from":1784989800,"p":7.5}]},"alarms":1})JSON"},
    {"06_cost_unconfigured", R"JSON({"v":1,"ts":1784984400,"ok":true,"age":3,"power":{"pv":2.9,"grid":-0.4,"batt":0.8,"home":1.7,"ev":0.0,"plant":2.1,"off_grid":false},"battery":{"soc":70.0,"soh":99.0,"capacity_kwh":16.0,"temp_c":24.5,"eta_min":110},"today":{"solar":12.4,"import":3.1,"export":5.2,"load":9.8,"charge":6.0,"discharge":4.2},"cost":{"configured":false},"alarms":0})JSON"},
    {"07_today_null", R"JSON({"v":1,"ts":1784984400,"ok":true,"age":3,"power":{"pv":3.1,"grid":-0.9,"batt":1.0,"home":1.2,"ev":0.0,"plant":2.1,"off_grid":false},"battery":{"soc":66.0,"soh":99.0,"capacity_kwh":16.0,"temp_c":24.5,"eta_min":104},"today":null,"cost":{"configured":true,"saving_gbp":1.23,"rate_p":7.5,"next":[{"from":1784986200,"p":23.1},{"from":1784988000,"p":7.5},{"from":1784989800,"p":7.5}]},"alarms":0})JSON"},
    {"08_registers_null", R"JSON({"v":1,"ts":1784984400,"ok":false,"age":12,"power":{"pv":null,"grid":null,"batt":null,"home":null,"ev":null,"plant":null,"off_grid":false},"battery":{"soc":null,"soh":null,"capacity_kwh":16.0,"temp_c":null,"eta_min":null},"today":{"solar":12.4,"import":3.1,"export":5.2,"load":9.8,"charge":6.0,"discharge":4.2},"cost":{"configured":true,"saving_gbp":1.23,"rate_p":7.5,"next":[{"from":1784986200,"p":23.1},{"from":1784988000,"p":7.5},{"from":1784989800,"p":7.5}]},"alarms":0})JSON"},
    {"09_stale", R"JSON({"v":1,"ts":1784984400,"ok":true,"age":187,"power":{"pv":2.2,"grid":-0.3,"batt":0.6,"home":1.3,"ev":0.0,"plant":1.6,"off_grid":false},"battery":{"soc":72.0,"soh":99.0,"capacity_kwh":16.0,"temp_c":24.5,"eta_min":100},"today":{"solar":12.4,"import":3.1,"export":5.2,"load":9.8,"charge":6.0,"discharge":4.2},"cost":{"configured":true,"saving_gbp":1.23,"rate_p":7.5,"next":[{"from":1784986200,"p":23.1},{"from":1784988000,"p":7.5},{"from":1784989800,"p":7.5}]},"alarms":0})JSON"},
};

static const size_t DEV_FIXTURE_COUNT = sizeof(DEV_FIXTURES) / sizeof(DEV_FIXTURES[0]);
